version: '3'
services:
  redis:
    image: redis
    container_name: yggdrasil-redis
    restart: always
    networks:
      - yggdrasil-net
    ports:
      - "6379:6379"
    command:
      --requirepass redis@6379
    volumes:
      - /docker/redis/data:/data
      - /docker/redis/conf/redis.conf:/etc/redis/redis.conf

  mysql:
    image: mysql
    container_name: yggdrasil-mysql
    restart: always
    networks:
      - yggdrasil-net
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql@3306
    volumes:
      - /docker/mysql/data:/var/lib/mysql
      - /docker/mysql/conf:/etc/mysql/conf.d
      - /docker/mysql/log:/var/log/mysql

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: yggdrasil-zookeeper
    restart: always
    networks:
      - yggdrasil-net
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: yggdrasil-kafka
    restart: always
    networks:
      - yggdrasil-net
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=43.139.11.51:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://43.139.11.51:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092

  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: yggdrasil-kafka-manager
    restart: always
    networks:
      - yggdrasil-net
    ports:
      - "19092:19092"
    environment:
      ZK_HOSTS: 43.139.11.51:2181
      KAFKA_MANAGER_USERNAME: kafka_manager
      KAFKA_MANAGER_PASSWORD: kafka_manager@19092
      KM_ARGS: -Dhttp.port=19092

  kafka-ui-lite:
    image: freakchicken/kafka-ui-lite
    container_name: yggdrasil-kafka-ui-lite
    restart: always
    networks:
      - yggdrasil-net
    ports:
      - "8889:8889"

  nacos:
    image: nacos/nacos-server
    container_name: yggdrasil-nacos
    restart: always
    networks:
      - yggdrasil-net
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"

  nginx:
    image: nginx
    container_name: yggdrasil-nginx
    restart: always
    ports:
      - "80:80"
    privileged: true
    networks:
      - yggdrasil-net
    volumes:
      - /docker/nginx/conf/conf.d:/etc/nginx/conf.d
      - /docker/nginx/log:/var/log/nginx
      - /docker/nginx/html:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime

networks:
  yggdrasil-net:
    external: false