version: '3'
services:
  redis:
    image: redis:latest
    container_name: yggdrasil-redis
    restart: always
    environment:
      - REDIS_PASSWORD=redis@6379
    networks:
      - yggdrasil-net
    ports:
      - 6379:6379
    env_file: .env

  mysql:
    image: mysql:latest
    container_name: yggdrasil-mysql
    restart: always
    networks:
      - yggdrasil-net
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: mysql@3306
    env_file: .env

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: yggdrasil-zookeeper
    restart: always
    networks:
      - yggdrasil-net
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: yggdrasil-kafka
    restart: always
    networks:
      - yggdrasil-net
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://43.139.11.51:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092

  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: yggdrasil-kafka-manager
    restart: always
    networks:
      - yggdrasil-net
    ports:
      - "19092:19092"
    environment:
      ZK_HOSTS: zookeeper:2181
      KAFKA_MANAGER_USERNAME: kafka#manager
      KAFKA_MANAGER_PASSWORD: kafka#manager@19092
      KM_ARGS: -Dhttp.port=19092

  nacos:
    image: nacos/nacos-server
    container_name: yggdrasil-nacos
    restart: always
    networks:
      - yggdrasil-net
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
    env_file: .env

  nginx:
    image: nginx
    container_name: yggdrasil-nginx
    restart: always
    ports:
      - "80:80"
    privileged: true
    networks:
      - yggdrasil-net

networks:
  yggdrasil-net:
    external: false