version: '3'
services:
  #消息中心
  bus-server:
    image: yggdrasil/yggdrasil-bus:latest
    container_name: yggdrasil-bus
    restart: always
    networks:
      - yggdrasil-net
    ports:
      - "8071:8071"
    env_file: .env
    environment:
      TZ: Asia/Guangzhou
