server:
  port: 8001

spring:
  application:
    name: yggdrasil-authentication-server
  main:
    allow-circular-references: true
  cloud:
    nacos:
      discovery:
        server-addr: 43.139.11.51:8848
        namespace: e5035c6b-7174-4713-bd39-4ffb2bf60f92
        group: YGGDRASIL_GROUP
    stream:
      kafka:
        binder:
          brokers: 43.139.11.51:9092
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info
