server:
  port: 8085

spring:
  application:
    name: yggdrasil-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    nacos:
      discovery:
        server-addr: 43.139.11.51:8848
        namespace: e5035c6b-7174-4713-bd39-4ffb2bf60f92
        group: YGGDRASIL_GROUP
    stream:
      kafka:
        binder:
          brokers: 43.139.11.51:9092

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
#自定义配置
gateway:
  nacos:
    server-addr: ${spring.cloud.nacos.discovery.server-addr}
    namespace: e5035c6b-7174-4713-bd39-4ffb2bf60f92
    data-id: dynamic-routing.json
    group: YGGDRASIL_GROUP
